### ISSUE TITLE
[QUESTION] Go To Definition 

### ISSUE THREAD

**Issue by aparkitny** [cap-js/cds-intellij#18] opened 2024-04-11 14:01 UTC
### Question

Hi, I installed the plugin as described in IntelliJ Ultimate edition. The .cds files are recognized and basic syntax coloring works, but besides that, it does not recognize any entity types and navigating to a type does also not work for me. I'm not sure why, but I guess it has something to do with my local setup. Any hints or ideas why that could be?

**Comment by rjayasinghe** [comment] 2024-04-12 10:01
It stopped working for me after updating IntelliJ 2024.1 :-( So I can confirm this and it's most probably a bug. @tim-sh have you seen this, too?

**Comment by tim-sh** [comment] 2024-04-12 11:30
Hi @aparkitny and @rjayasinghe,
I cannot confirm this. Could you please share your respective [IDE logs](https://github.com/cap-js/cds-intellij?tab=readme-ov-file#ide-logs)?
Thanks and best regards,
Tim

**Comment by rjayasinghe** [comment] 2024-04-12 11:48
> Hi @aparkitny and @rjayasinghe, I cannot confirm this. Could you please share your respective [IDE logs](https://github.com/cap-js/cds-intellij?tab=readme-ov-file#ide-logs)? Thanks and best regards, Tim

**Of course** this works now. 😅 But I clearly can remember that I had this issue last week or the week before and registered that it does not work anymore. But maybe that was just with the last patch level of 2023.4 ..

@aparkitny can you still reproduce the issue and if yes please share the exact IntelliJ version and debug logs.

**Comment by aparkitny** [comment] 2024-04-15 08:05
Hi, I still can reproduce this. It does not work for me. I'm using IntelliJ IDEA 2024.1 (Ultimate Edition)
Build #IU-241.14494.240.  idea.log attached.
[idea.log](https://github.com/cap-js/cds-intellij/files/14975887/idea.log)

**Comment by tim-sh** [comment] 2024-04-15 21:10
@aparkitny The log file is empty when downloaded.
Anyway, could you please retry with the latest [release](https://github.com/cap-js/cds-intellij/releases) built for 2024.1?

**Comment by aparkitny** [comment] 2024-04-16 07:06
@tim-sh. Sorry, my bad, here is the correct log file 
[idea.log](https://github.com/cap-js/cds-intellij/files/14988135/idea.log)

Besides that, I have the latest version installed, from April 4th

**Comment by tim-sh** [comment] 2024-04-16 10:04
@aparkitny Thanks for the log. However, I can't find a hint on any erroneous behavior with regards to the CDS Language Support plugin or its handling by the IDE.

Please also share the file `C:\Users\D052607\AppData\Roaming\JetBrains\IntelliJIdea2024.1\plugins\intellij-cds\lib\cds-lsp\stdio.log`. And could you clarify since which IDE or plugin update it stopped working (if so)?

**Comment by aparkitny** [comment] 2024-04-16 11:34
@tim-sh What operating System you are using? I am using Windows.

**Comment by tim-sh** [comment] 2024-04-16 12:25
Linux here, but I'll test this on Windows. If you could share the additional info, that'd also be helpful.

**Comment by rjayasinghe** [comment] 2024-04-16 13:42
I am on MacOS btw.. :)

**Comment by aparkitny** [comment] 2024-04-17 07:30
ok, here is the additional requested log file
[stdio.log](https://github.com/cap-js/cds-intellij/files/15007490/stdio.log)

**Comment by tim-sh** [comment] 2024-04-19 07:15
@aparkitny The LSP server does send technically valid responses, but they are empty for some reason. I'll follow up on that.
In the meantime, as you seem to be using plugin version 7.2.1., please upgrade to the newest [7.3.0](https://github.com/cap-js/cds-intellij/releases/tag/7.3.0) build for IntelliJ 2024.1. If it still does not work, please share the newest stdio.log.
Thank you.

**Comment by aparkitny** [comment] 2024-04-19 08:27
@tim-sh I updated the plugin to the newest version, it still does not work. Newest [stdio.log](https://github.com/cap-js/cds-intellij/files/15037444/stdio.log). 
Thanks

**Comment by aparkitny** [comment] 2024-04-23 07:03
@tim-sh the requested logs: 
[stdio.log](https://github.com/cap-js/cds-intellij/files/15072656/stdio.log)
[cdxlsp_logs.zip](https://github.com/cap-js/cds-intellij/files/15072646/cdxlsp_logs.zip)
[idea.log](https://github.com/cap-js/cds-intellij/files/15072696/idea.log)

**Comment by tim-sh** [comment] 2024-04-30 15:07
@aparkitny This will be fixed with the next release, expected this week.

**Closed by tim-sh** 2024-04-30 15:07 UTC
Labels: bug, question, author action
